config/routes.rb
Rails.application.routes.draw do
 root 'forecasts#index'

 get '/forecast/create' => 'forecasts#create'

 get '/login' => 'sessions#new'
 post '/login' => 'sessions#create'
 get '/logout' => 'sessions#destroy'

 get '/users/:id' => 'user#show', as: "user"
 get '/signup' => 'user#new'
 post '/users' => 'user#create' 
 get '/users' => 'user#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forecast.rb
class Forecast < ApplicationRecord
	extend ActiveModel::Naming
 	
	attr_accessor :location

	def initialize(location, forecast_io_object)
		@forecast_io_object = forecast_io_object
		self.location = location
	end

	def self.request(attributes)
		geo = ::Geocoder.search(attributes[:location]).first
		self.new attributes[:location], ForecastIO.forecast(geo.latitude, geo.longitude,  params: { units: 'si' })
	end

	def daily_summary
		@forecast_io_object.daily.summary
	end

	def daily_icon
		@forecast_io_object.daily.daily_icon
	end

	def daily
		@forecast_io_object.daily.data
	end

	def currently
		@forecast_io_object.currently
	end
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, uniqueness: true, presence: true 
	validates :name, presence: true
	validates :role, presence: true 
	enum role: { :user => 0, :superuser => 1, :admin => 2}
	has_secure_password

	def self.search(search)
		where("name ILIKE ?", "%#{search}%")
	end

	def authorized

		if self.role == "superuser" || "admin"
			"You are a super user"
		end
	end
		
	



	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
 
  private 

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  

  def authorize
  	if current_user.role != ("admin" || "superuser")
  		redirect_to '/'
  		flash[:notice] = "You are not authorized to perform this action"
  	else 
  		flash[:notice] = "You are authorized to perform this action"
  	end

  	
  end
 
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
	before_action :authorize, :except => [:index]

	def index
		
	end

	def create

		@forecast = Forecast.request(params[:forecast])

	end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by_email(params[:email])
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to '/'
		else 
			redirect_to '/login'
		end

	end

	def destroy
		session[:user_id] = nil
		redirect_to '/login'
	end 
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	

	def new
		
	end

	def create
		@user = User.new(user_params)
		
		if @user.save 
			session[:user_id] = @user.id
			redirect_to '/'
		else
			redirect_to '/signup'
		end
	end


	def show
		@user = User.find(params[:id])
	end

	def index
		@users = User.all
		if params[:search]
			@users = User.search(params[:search]).page(params[:page]).order("created_at DESC")
			respond_to do |format|
				format.html {redirect_to users_path}
				format.js
			end
		else

		
			@users = User.all.page(params[:page]).order('created_at DESC')
		end
	end




	private

	def user_params
		params.require(:user).permit(:name, :password, :email, :password_confirmation, :role)

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
	def day_from_timestamp(ts)
    Time.at(ts).strftime('%A')
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
	def search
    geo_response = ::Geocoder.search(params[:query])
    response = geo_response.map do |node|
      {value: node.formatted_address, lat: node.latitude, lng: node.longitude}
    end
    render json: response
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/forecasts/_request_forecast_widget.html.erb
<div class="widget request-forecast">
  <%= form_for :forecast, url: forecast_create_path, method: 'GET' do |f| %>
      <%= f.label :location, "Location" %>
      <%= f.text_field :location  %>
      <%= f.submit 'Go' %>
  <% end %>

</div>

app/views/forecasts/_todays_forecast_results.html.erb
<div class="widget todays-forecast col-md-4">
  <div class="widget-box inner">
    <div class="highlight text-center">Todays Forecast</div>
    <div class="results">
      <p class="lead text-center">For <%= forecast.location %></p>
      <p>Summary: <%= forecast.currently.summary %></p>
      <i class="wi wi-forecast-io-<%= forecast.currently.icon %>"></i> 
      <p>Temperature: <%= forecast.currently.temperature %></p>
    </div>
  </div>
</div>

app/views/forecasts/_weekly_forecast_results.html.erb
<div class="widget weekly-forecast col-md-8">
  <div class="widget-box inner">
    <div class="highlight text-center">Weekly Forecast</div>
    <div class="results">
     
      <p class="lead text-center">For <%= forecast.location %></p>
      <p>Summary: <%= forecast.daily_summary %></p>
      <% forecast.daily.each do |day_forecast| %>
          <h4>Day: <%= day_from_timestamp day_forecast.time %></h4>
          <p><i class="wi wi-forecast-io-<%= day_forecast.icon%>"></i> <%= day_forecast.summary %></p>
          <p>Temperature: <%= day_forecast.temperatureMin %> to <%= day_forecast.temperatureMax %></p>
      <% end %>
      
    </div>
  </div>
</div>

app/views/forecasts/create.html.erb
<div class="container">
 
  <%= render partial: 'request_forecast_widget', locals: {forecast: @forecast} 	%>
  <div class="row">
    <%= render partial: 'todays_forecast_results', locals: {forecast: @forecast} %>
    <%= render partial: 'weekly_forecast_results', locals: {forecast: @forecast} %>
  </div>
</div>

app/views/forecasts/index.html.erb
<div class="container">
	<% if current_user %>
  <%= render partial: 'request_forecast_widget', locals: {forecast: @forecast} %>
  	<% else %>
  	<p>Please Sign in to make a forecast </p>
  	<% end %>
</div>

app/views/forecasts/new.html.erb
<div class="container">
  <%= render partial: 'intro' %>
  <%= render partial: 'request_forecast_widget', locals: {forecast: @forecast} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cloudwatch</title>
    <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

  </head>

  <body>
    <% if current_user %>
  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>
  	 <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">Cloudwatch</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"> 
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
    
      <li class="nav-item">
        <% if !current_user %>
        <%= link_to "Sign Up", signup_path, class:"nav-link" %> 
        <% end %>
      </li>
      <li class="nav-item">
        <% if !current_user %>
        <%= link_to "Sign In", login_path, class:"nav-link" %>
        <% end %>
      </li>
      <li class="nav-item">
        <% if current_user %>
        <%= link_to "My Profile", user_path(current_user), class:"nav-link" %>
        <% end %>
      </li>
        <% if current_user %>
      <li class="nav-item">
        <%= link_to "All users", users_path, class:"nav-link" %>
      </li>
        <% end %>

    </ul>
    
  </div>
  
</nav>
    <div class="container">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

app/views/user/_form.html.erb
<h1>Signup</h1>

<%= form_for :user, url: '/users' do |f| %>

	Name: <%= f.text_field :name %>
	Email: <%= f.text_field :email %>
	Password: <%= f.password_field :password %>
	Password Confirmation: <%= f.password_field :password_confirmation %>


	
	<%= f.select(:role) do %>
		<% [['user'],['superuser'],['admin']].each do |c| %>
			<%= content_tag(:option, c.first, value: c.last) %>
			<% end %>
		<% end %>
	<%= f.submit "Submit" %>
<% end %>

app/views/user/_results.html.erb
<div class="row"  id="user-results">

		
			<div class="panel-heading">
				Users
			</div>
			<div class="panel-body">
				<% if @users.empty? == false %>
				<%= will_paginate @users %>

				<% @users.each do |l| %>
					<div class="row">
						<div class="col-md-2">
							<p class="user_name"><%= l.name %></p>
							<p class="email"><%= l.email %></p>
							<p class="role"><%= l.role %></p>
						</div>
					</div>
				<% end %>
				<% end %>
			</div>
		
	
</div>

app/views/user/index.html.erb
<div class= "panel panel-default"> 
	<div class= "panel-body">
		<% if @users.blank? %>
			<h4>There are no users matching the term <%= params[:search] %>.</h4>
		<% end %>
	</div>
</div> 
<div class="container">
	      <%= form_tag(users_path, :method=> "get", id: "search-form", remote: true)  do %>
        <%= text_field_tag :search, params[:search], placeholder:"search for users", class:"form-control mr-sm-2", :required => 'required' %>
        <%= submit_tag "Search", :name => nil, id: "submit-search" %>
      <% end %>
	
    <br>
	
</div>

app/views/user/index.js.erb
// 	$("#submit-search").click(function(){
//     $("#user_name").append("@user.name");
//     $("#email").append("@user.email");
//     $("#role").append("@user.role");
// });
	
	if ($("#user-results").length !== 0){
		
		$("#user-results").remove()

	}
	else {

	 	$("#submit-search").after("<%= escape_javascript(render partial: 'results', locals: { user: @users} ) %>"); 
	}
	

app/views/user/new.html.erb
<%= render partial: "form" %>

app/views/user/show.html.erb
<div class="container">
<p><%= current_user.name %></p>
</div>